### ISSUE TITLE
Adding New Chapter and Deleting Existing Text Broken

### ISSUE THREAD

**Issue by deno2** [rtfeldman/dreamwriter#27] opened 2015-01-16 17:19 UTC
On my Mac in Chrome if I do:

1. Click + to add a new chapter.
2. Double click the default new chapter name to select the text.
3. Press the Backspace key to delete the existing text.

Then:

1. The browser interprets that as meaning "Go Back" i.e. the keyboard shortcut for the browser back button.

Also if I select the text and then just type - nothing happens. The normal behaviour of a textbox would be to replace the selected text with the new characters typed.

**Comment by rtfeldman** [comment] 2015-01-16 17:46
I see - the issue is that the way to edit chapter names is directly in the text, rather than in the sidebar. In other words, double-clicking the sidebar has no effect, so backspace defaults to its normal function (going back a page).

However, this seems like a totally sensible way to use the sidebar, so I'll change it to highlight the text when you click a chapter in the sidebar.

Thanks for pointing this out!

**Comment by deno2** [comment] 2015-01-16 17:49
Cool. No worries. Very nice app by the way!

**Comment by rtfeldman** [comment] 2015-01-16 18:28
Thanks! :smiley_cat:

**Comment by rtfeldman** [comment] 2015-02-09 00:15
Fixed in b5c05cffaad44488142424e1b400e103b3580bd7

**Closed by rtfeldman** 2015-02-09 00:15 UTC
Labels: bug
